// Pure data module — no "use client" — safe to import in both server and client components

export type TaxCategory = "all" | "territorial" | "flat-rate" | "treaty";

export interface CountryCard {
  slug: string;
  country: string;
  flag: string;
  region: string;
  category: "territorial" | "flat-rate" | "treaty";
  categoryLabel: string;
  taxAngle: string;
  program: string;
  bestFor: string;
  cardHook: string;
  officialLinkLabel: string;
  officialLink: string;
  seoSummary: string;
  verificationStatus: "ok" | "check";
  taxDisplay: string;
  taxDisplaySubtext: string;
  imageUrl: string;
  imageAlt: string;
}

export interface FaqItem {
  question: string;
  answer: string;
}

const FALLBACK_IMG =
  "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80";

export const taxGuideCountries: CountryCard[] = [
  // ── TERRITORIAL TAX SYSTEMS ───────────────────────────────────
  {
    slug: "panama",
    country: "Panama",
    flag: "🇵🇦",
    region: "Latin America",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "Foreign-source income may not be taxed locally",
    program: "Pensionado Visa",
    bestFor: "Retirees with US pension or Social Security income",
    cardHook:
      "Panama's Pensionado program is one of the world's most established retirement visa pathways. Under Panama's territorial tax system, foreign-source income may not be subject to local taxation — depending on residency status and income type. Verify official rules before making tax or residency decisions.",
    officialLinkLabel: "Panama Migration Authority",
    officialLink: "https://www.migracion.gob.pa/",
    seoSummary:
      "Panama offers a territorial tax system and the Pensionado Visa for retirees. Foreign-source income may qualify for favorable treatment. Verify official rules before making tax or residency decisions.",
    verificationStatus: "check",
    taxDisplay: "0%",
    taxDisplaySubtext: "on foreign-source income",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Panama canal and skyline",
  },
  {
    slug: "costa-rica",
    country: "Costa Rica",
    flag: "🇨🇷",
    region: "Latin America",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "Pension income from abroad may not be taxed locally",
    program: "Pensionado / Rentista Residency",
    bestFor: "Retirees seeking warm climate with established expat community",
    cardHook:
      "Costa Rica's territorial tax system generally does not tax income earned outside the country. The Pensionado and Rentista programs offer structured residency paths for qualifying retirees. Foreign pension income may qualify for favorable treatment depending on residency status.",
    officialLinkLabel: "Costa Rica DGME (Immigration)",
    officialLink: "https://www.dgme.go.cr/",
    seoSummary:
      "Costa Rica has a territorial tax system and offers Pensionado residency for retirees. Foreign pension income may not be taxed locally. Verify all rules with official sources.",
    verificationStatus: "check",
    taxDisplay: "0%",
    taxDisplaySubtext: "on foreign-source income",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Costa Rica rainforest and waterfall",
  },
  {
    slug: "belize",
    country: "Belize",
    flag: "🇧🇿",
    region: "Latin America",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "QRP holders may not pay local tax on foreign-source income",
    program: "Qualified Retired Persons (QRP) Programme",
    bestFor: "English-speaking retirees seeking Caribbean lifestyle",
    cardHook:
      "Belize's Qualified Retired Persons program is one of the Caribbean's oldest formal retiree programs. QRP status may allow holders to live in Belize without paying local income tax on foreign-source income — verify current official program rules and eligibility requirements.",
    officialLinkLabel: "Belize QRP Programme",
    officialLink: "https://www.irs.gov/individuals/international-taxpayers",
    seoSummary:
      "Belize QRP program offers residency with potential exemption from local tax on foreign income. Verify official QRP eligibility rules and current program status before applying.",
    verificationStatus: "check",
    taxDisplay: "0%",
    taxDisplaySubtext: "on foreign-source income",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Belize Caribbean reef and coast",
  },
  {
    slug: "nicaragua",
    country: "Nicaragua",
    flag: "🇳🇮",
    region: "Latin America",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "Pensioner residency program with territorial tax structure",
    program: "Law 694 Retirement Residency",
    bestFor: "Retirees seeking very low cost of living with Pacific coastline",
    cardHook:
      "Nicaragua's Law 694 created a dedicated retirement residency program with various incentives. Nicaragua's territorial tax approach means foreign-source income may not be taxed locally, depending on residency status and current regulations.",
    officialLinkLabel: "Nicaragua DGI (Tax Authority)",
    officialLink: "https://www.irs.gov/individuals/international-taxpayers",
    seoSummary:
      "Nicaragua Law 694 offers retirement residency with potential tax benefits. Foreign-source income treatment depends on residency status. Verify official rules before making any decisions.",
    verificationStatus: "check",
    taxDisplay: "0%",
    taxDisplaySubtext: "on foreign-source income",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Nicaragua volcano and colonial city",
  },
  {
    slug: "guatemala",
    country: "Guatemala",
    flag: "🇬🇹",
    region: "Central America",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "Foreign-source income may not be taxed locally",
    program: "Rentista Residency / Pensioner Visa",
    bestFor: "Retirees drawn to Antigua's colonial charm and volcanic highlands",
    cardHook:
      "Guatemala's territorial tax framework focuses taxation on locally-sourced income. The Rentista residency provides a pathway for retirees with qualifying foreign income. Antigua Guatemala, Lake Atitlán, and the highlands offer a rich cultural setting at very low costs. Verify current rules with SAT Guatemala.",
    officialLinkLabel: "SAT Guatemala (Tax Authority)",
    officialLink: "https://portal.sat.gob.gt/",
    seoSummary:
      "Guatemala's territorial tax system may not tax foreign-source income locally. Rentista residency available for qualifying retirees. Verify all rules before making tax or residency decisions.",
    verificationStatus: "check",
    taxDisplay: "0%",
    taxDisplaySubtext: "on foreign-source income",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Guatemala Antigua colonial architecture and volcano",
  },
  {
    slug: "uruguay",
    country: "Uruguay",
    flag: "🇺🇾",
    region: "South America",
    category: "flat-rate",
    categoryLabel: "Flat-Rate Program",
    taxAngle: "New residents may qualify for a 10-year option on foreign-source income",
    program: "Uruguay Residency — Foreign Income Tax Option",
    bestFor: "Retirees seeking South American stability with European-style culture",
    cardHook:
      "Uruguay may offer new tax residents an election to either not pay local income tax on foreign-source income for up to 10 years, or to apply a low flat rate. Uruguay is frequently cited as South America's most stable, transparent, and retiree-friendly country. Verify current rules with DGI.",
    officialLinkLabel: "DGI Uruguay (Tax Authority)",
    officialLink: "https://www.dgi.gub.uy/",
    seoSummary:
      "Uruguay may offer qualifying new residents a 10-year option on foreign income treatment. Rules depend on residency classification. Verify current rules with DGI Uruguay and a qualified advisor.",
    verificationStatus: "check",
    taxDisplay: "Tax Holiday",
    taxDisplaySubtext: "foreign-income option",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Montevideo Uruguay coast",
  },
  {
    slug: "paraguay",
    country: "Paraguay",
    flag: "🇵🇾",
    region: "South America",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "Paraguay taxes only locally-sourced income",
    program: "Rentista / Pensioner Residency",
    bestFor: "Retirees seeking very low-cost South American base",
    cardHook:
      "Paraguay operates a strict territorial tax system — only income earned within Paraguay is generally subject to local taxation. Foreign pension income, Social Security, or investment returns sourced abroad may not be taxed locally, depending on residency status.",
    officialLinkLabel: "Paraguay SET (Tax Authority)",
    officialLink: "https://www.set.gov.py/",
    seoSummary:
      "Paraguay has a territorial tax system taxing only locally-sourced income. Foreign pension income may not be subject to local tax. Verify official rules and residency requirements.",
    verificationStatus: "check",
    taxDisplay: "0%",
    taxDisplaySubtext: "on foreign-source income",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Paraguay South America landscape",
  },
  {
    slug: "ecuador",
    country: "Ecuador",
    flag: "🇪🇨",
    region: "South America",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "Foreign pension income may qualify for favorable treatment",
    program: "Retirement / Pensioner Residency Visa",
    bestFor: "Budget-focused retirees, particularly in Cuenca or the coast",
    cardHook:
      "Ecuador offers dedicated retirement residency for those with qualifying pension income. Ecuador's tax framework may offer favorable treatment for foreign-source pension income — verify current rules with official Ecuadorian tax and immigration authorities.",
    officialLinkLabel: "Ecuador Ministry of Foreign Affairs",
    officialLink: "https://www.cancilleria.gob.ec/",
    seoSummary:
      "Ecuador retirement residency visa available for pensioners. Foreign pension income may receive favorable tax treatment depending on applicable rules. Verify all rules with a qualified advisor.",
    verificationStatus: "check",
    taxDisplay: "0%",
    taxDisplaySubtext: "on foreign-source income",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Ecuador Quito and Andes mountains",
  },
  {
    slug: "bolivia",
    country: "Bolivia",
    flag: "🇧🇴",
    region: "South America",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "Bolivia taxes only locally-sourced income",
    program: "Temporary / Permanent Residency for Pensioners",
    bestFor: "Ultra-budget retirees; adventurous lifestyle in Sucre or La Paz",
    cardHook:
      "Bolivia's territorial tax system taxes only income generated within Bolivia. For retirees living on foreign pension income or US Social Security, this may mean limited local tax exposure — depending on residency classification and current regulations.",
    officialLinkLabel: "Bolivia Tax Authority (Impuestos Nacionales)",
    officialLink: "https://www.impuestos.gob.bo/",
    seoSummary:
      "Bolivia uses a territorial tax system. Foreign-source income may not be taxed locally. Verify official rules, residency requirements, and consult a qualified advisor before making decisions.",
    verificationStatus: "check",
    taxDisplay: "0%",
    taxDisplaySubtext: "on foreign-source income",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Bolivia Uyuni salt flats",
  },
  {
    slug: "malaysia",
    country: "Malaysia",
    flag: "🇲🇾",
    region: "Southeast Asia",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "Offshore income may not be subject to local tax",
    program: "Malaysia My Second Home (MM2H)",
    bestFor: "Retirees seeking a modern, English-friendly Asian base",
    cardHook:
      "Malaysia's MM2H program offers a long-term residence visa for retirees. Foreign-source income remitted to Malaysia may qualify for favorable treatment, depending on residency status and applicable rules. Program requirements and eligibility have changed — verify current official rules.",
    officialLinkLabel: "Malaysia MM2H Programme",
    officialLink: "https://www.irs.gov/individuals/international-taxpayers",
    seoSummary:
      "Malaysia MM2H visa offers long-term residency. Foreign-source income may receive favorable tax treatment depending on rules in effect. Verify current program requirements before applying.",
    verificationStatus: "check",
    taxDisplay: "0%",
    taxDisplaySubtext: "on foreign-source income",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Kuala Lumpur Malaysia skyline",
  },
  {
    slug: "philippines",
    country: "Philippines",
    flag: "🇵🇭",
    region: "Southeast Asia",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "Foreign-source income generally not taxed locally for SRRV holders",
    program: "Special Resident Retiree's Visa (SRRV)",
    bestFor: "Retirees seeking an English-speaking, affordable Southeast Asian base",
    cardHook:
      "The Philippines offers the SRRV, a dedicated retirement visa with potential benefits including favorable local tax treatment on foreign-source income. The Philippines uses a semi-territorial approach for certain non-resident income categories. Verify current SRRV rules.",
    officialLinkLabel: "Philippines Retirement Authority",
    officialLink: "https://www.pra.gov.ph/",
    seoSummary:
      "Philippines SRRV provides a dedicated retirement visa. Foreign-source income may not be taxed locally for qualifying holders. Verify official program rules before making any decisions.",
    verificationStatus: "check",
    taxDisplay: "0%",
    taxDisplaySubtext: "on foreign-source income",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Philippines tropical beach and island",
  },
  {
    slug: "vanuatu",
    country: "Vanuatu",
    flag: "🇻🇺",
    region: "Pacific",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "No personal income tax; no capital gains or inheritance tax",
    program: "Vanuatu Resident Visa / Development Support Programme",
    bestFor: "Retirees seeking a tax-free Pacific island lifestyle with simple residency",
    cardHook:
      "Vanuatu levies no personal income tax, no capital gains tax, and no inheritance tax. The Republic of Vanuatu offers resident visa pathways and has been recognized internationally for its zero-tax framework. Verify current residency eligibility requirements and any applicable fees with official Vanuatu authorities.",
    officialLinkLabel: "Vanuatu Department of Immigration",
    officialLink: "https://www.irs.gov/individuals/international-taxpayers",
    seoSummary:
      "Vanuatu has no personal income tax, capital gains tax, or inheritance tax. Resident visa available for qualifying individuals. Verify current program requirements before applying.",
    verificationStatus: "check",
    taxDisplay: "0%",
    taxDisplaySubtext: "on foreign-source income",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Vanuatu Pacific island paradise",
  },
  {
    slug: "united-arab-emirates",
    country: "United Arab Emirates",
    flag: "🇦🇪",
    region: "Middle East",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "No personal income tax on individuals in the UAE",
    program: "UAE Retirement Visa / Golden Visa",
    bestFor: "Retirees seeking a modern, cosmopolitan lifestyle with zero income tax",
    cardHook:
      "The UAE levies no personal income tax on individuals. Dubai and Abu Dhabi offer world-class infrastructure, English as the primary business language, and a cosmopolitan lifestyle. The UAE Retirement Visa provides a structured residency pathway for those aged 55 and above who meet financial eligibility criteria.",
    officialLinkLabel: "UAE Federal Authority for Identity and Citizenship",
    officialLink: "https://icp.gov.ae/",
    seoSummary:
      "The UAE has no personal income tax. Retirement and Golden Visa programs available for qualifying individuals. Verify current visa requirements and financial thresholds with official UAE authorities.",
    verificationStatus: "check",
    taxDisplay: "0%",
    taxDisplaySubtext: "personal income tax",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Dubai UAE modern skyline",
  },
  {
    slug: "qatar",
    country: "Qatar",
    flag: "🇶🇦",
    region: "Middle East",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "No personal income tax for individuals in Qatar",
    program: "Qatar Permanent Residency Programme",
    bestFor: "Retirees seeking a Gulf lifestyle with zero personal income tax",
    cardHook:
      "Qatar imposes no personal income tax on individuals. As one of the world's wealthiest nations per capita, Qatar offers modern infrastructure, excellent healthcare, and a rapidly growing expat community. The Qatar Permanent Residency Programme provides limited pathways for qualifying foreigners. Verify current eligibility requirements.",
    officialLinkLabel: "Qatar Ministry of Interior",
    officialLink: "https://www.moi.gov.qa/",
    seoSummary:
      "Qatar has no personal income tax. Permanent residency pathways are available for qualifying individuals. Verify current program requirements with official Qatari authorities.",
    verificationStatus: "check",
    taxDisplay: "0%",
    taxDisplaySubtext: "personal income tax",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Qatar Doha skyline and waterfront",
  },
  {
    slug: "bahamas",
    country: "Bahamas",
    flag: "🇧🇸",
    region: "Caribbean",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "No income tax, capital gains tax, or inheritance tax",
    program: "Bahamas Annual / Permanent Residency",
    bestFor: "Retirees seeking a tropical English-speaking Caribbean base with zero income tax",
    cardHook:
      "The Bahamas levies no personal income tax, no capital gains tax, and no inheritance tax. As a stable, English-speaking nation close to the United States, it is a well-established retirement destination. Annual and permanent residency programs are available for qualifying individuals who meet financial requirements.",
    officialLinkLabel: "Bahamas Department of Immigration",
    officialLink: "https://www.irs.gov/individuals/international-taxpayers",
    seoSummary:
      "The Bahamas has no income tax, capital gains tax, or inheritance tax. Residency programs available for qualifying individuals. Verify current program requirements before applying.",
    verificationStatus: "check",
    taxDisplay: "0%",
    taxDisplaySubtext: "personal income tax",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Bahamas Caribbean beach and turquoise water",
  },

  // ── FLAT-RATE & SPECIAL PROGRAMS ──────────────────────────────
  {
    slug: "greece",
    country: "Greece",
    flag: "🇬🇷",
    region: "Mediterranean Europe",
    category: "flat-rate",
    categoryLabel: "Flat-Rate Program",
    taxAngle: "Qualifying retirees may pay a 7% flat tax on foreign income",
    program: "Article 5B — Alternative Tax for Foreign Retirees",
    bestFor: "Retirees seeking Mediterranean sun and EU residency",
    cardHook:
      "Greece's Article 5B program allows qualifying foreign retirees who transfer their tax residency to Greece to pay a flat 7% tax on foreign-source income, rather than standard progressive rates. Specific eligibility conditions and annual minimum tax apply — consult a qualified international tax advisor.",
    officialLinkLabel: "AADE (Greece Independent Tax Authority)",
    officialLink: "https://www.aade.gr/",
    seoSummary:
      "Greece offers a 7% flat tax on foreign pension income for qualifying retirees who transfer tax residency. Specific conditions apply. Verify official rules with AADE and a qualified international tax advisor.",
    verificationStatus: "check",
    taxDisplay: "7%",
    taxDisplaySubtext: "flat tax program",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Greece Santorini and Aegean Sea",
  },
  {
    slug: "italy",
    country: "Italy",
    flag: "🇮🇹",
    region: "Mediterranean Europe",
    category: "flat-rate",
    categoryLabel: "Flat-Rate Program",
    taxAngle: "7% flat tax on foreign income in qualifying southern municipalities",
    program: "Article 24-ter — Retiree Flat-Tax Regime",
    bestFor: "Retirees drawn to Italian culture, cuisine, and southern landscapes",
    cardHook:
      "Italy's Article 24-ter offers qualifying foreign pension recipients who relocate to certain southern municipalities (populations under 20,000) a flat 7% tax on all foreign-source income. Specific municipality lists, eligibility criteria, and annual application requirements apply.",
    officialLinkLabel: "Agenzia delle Entrate (Italy Tax Authority)",
    officialLink: "https://www.agenziaentrate.gov.it/",
    seoSummary:
      "Italy Article 24-ter offers a 7% flat tax on foreign income for qualifying retirees in eligible southern municipalities. Strict eligibility conditions apply. Verify current rules with Agenzia delle Entrate.",
    verificationStatus: "check",
    taxDisplay: "7%",
    taxDisplaySubtext: "flat tax program",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Italy Amalfi Coast",
  },
  {
    slug: "cyprus",
    country: "Cyprus",
    flag: "🇨🇾",
    region: "Eastern Mediterranean",
    category: "flat-rate",
    categoryLabel: "Flat-Rate Program",
    taxAngle: "Non-Dom regime; potential favorable tax treatment on qualifying income",
    program: "Non-Domicile (Non-Dom) Residency Status",
    bestFor: "Retirees seeking EU residency in English-speaking Mediterranean island",
    cardHook:
      "Cyprus offers a Non-Domicile tax status that may provide favorable treatment for certain types of income. Cyprus is an EU member with English widely spoken. Verify eligibility conditions and applicable tax rates on pension income with a qualified Cypriot tax advisor.",
    officialLinkLabel: "Cyprus Tax Department",
    officialLink: "https://www.mof.gov.cy/",
    seoSummary:
      "Cyprus Non-Dom status may offer favorable tax treatment on qualifying income for eligible residents. EU member state with English widely used. Verify current eligibility rules before making decisions.",
    verificationStatus: "check",
    taxDisplay: "5%",
    taxDisplaySubtext: "pension tax option",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Cyprus Mediterranean coastline",
  },
  {
    slug: "malta",
    country: "Malta",
    flag: "🇲🇹",
    region: "Mediterranean Europe",
    category: "flat-rate",
    categoryLabel: "Flat-Rate Program",
    taxAngle: "Global Residence Programme with minimum annual tax; EU membership",
    program: "Malta Global Residence Programme / HNWI",
    bestFor: "Retirees seeking EU residency with English as an official language",
    cardHook:
      "Malta's Global Residence Programme and High Net Worth Individual programmes offer EU residency with a minimum annual tax arrangement and potentially favorable treatment on foreign income remitted to Malta. Malta is an EU member with English as an official language.",
    officialLinkLabel: "Malta CFR (Tax Authority)",
    officialLink: "https://cfr.gov.mt/",
    seoSummary:
      "Malta's Global Residence and HNWI programs offer EU residency with minimum tax arrangements. Foreign income treatment depends on whether it's remitted to Malta. Verify current program rules with CFR Malta.",
    verificationStatus: "check",
    taxDisplay: "15%",
    taxDisplaySubtext: "flat tax program",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Malta Valletta Grand Harbour",
  },
  {
    slug: "portugal",
    country: "Portugal",
    flag: "🇵🇹",
    region: "Western Europe",
    category: "flat-rate",
    categoryLabel: "Flat-Rate Program",
    taxAngle: "IFICI program; NHR successor for qualifying income categories",
    program: "IFICI (Incentive for International Scientific and Innovation Activities)",
    bestFor: "Retirees seeking EU lifestyle, English-friendliness, and tax efficiency",
    cardHook:
      "Portugal's Non-Habitual Resident (NHR) regime ended for new applicants in January 2024 and was succeeded by the IFICI program. Existing NHR holders may retain their status. IFICI targets specific income categories — verify current eligibility rules carefully before making any residency decisions.",
    officialLinkLabel: "AT — Portugal Tax and Customs Authority",
    officialLink: "https://www.portaldasfinancas.gov.pt/",
    seoSummary:
      "Portugal's NHR program ended for new applicants in 2024, replaced by IFICI. Rules vary significantly. Consult a qualified international tax advisor and verify current rules with Portugal's AT authority.",
    verificationStatus: "check",
    taxDisplay: "20%",
    taxDisplaySubtext: "possible flat rate",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Portugal Lisbon tram and cityscape",
  },
  {
    slug: "andorra",
    country: "Andorra",
    flag: "🇦🇩",
    region: "Western Europe",
    category: "flat-rate",
    categoryLabel: "Flat-Rate Program",
    taxAngle: "Low flat income tax with a generous basic exemption",
    program: "Andorra Active / Passive Residency",
    bestFor: "Retirees seeking a European mountain lifestyle with very low taxation",
    cardHook:
      "Andorra applies a flat 10% personal income tax rate with significant basic exemptions that may reduce or eliminate tax for lower-income retirees. Nestled between France and Spain in the Pyrenees, Andorra offers EU proximity, low VAT, and high quality of life. Verify current residency and tax rules with official Andorran authorities.",
    officialLinkLabel: "Govern d'Andorra (Government of Andorra)",
    officialLink: "https://www.govern.ad/",
    seoSummary:
      "Andorra has a 10% flat income tax with generous basic exemptions. Passive residency available for qualifying individuals. Verify current rules with official Andorran authorities.",
    verificationStatus: "check",
    taxDisplay: "10%",
    taxDisplaySubtext: "low-tax ceiling",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Andorra Pyrenees mountains and village",
  },
  {
    slug: "bulgaria",
    country: "Bulgaria",
    flag: "🇧🇬",
    region: "Eastern Europe",
    category: "flat-rate",
    categoryLabel: "Flat-Rate Program",
    taxAngle: "10% flat income tax — lowest in the EU",
    program: "Bulgaria Long-Term Residency (EU Member)",
    bestFor: "EU-seeking retirees wanting the lowest flat tax rate in the bloc",
    cardHook:
      "Bulgaria has the lowest flat income tax rate in the European Union at 10%. As an EU member, it offers long-term residency advantages and the Schengen Area lifestyle. Foreign income treatment depends on residency status — consult a qualified Bulgarian tax advisor.",
    officialLinkLabel: "Bulgaria NRA (National Revenue Agency)",
    officialLink: "https://nap.bg/",
    seoSummary:
      "Bulgaria has a 10% flat income tax — lowest in the EU. EU member state with accessible long-term residency. Verify foreign income tax treatment with the National Revenue Agency Bulgaria.",
    verificationStatus: "check",
    taxDisplay: "10%",
    taxDisplaySubtext: "flat income tax",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Bulgaria Sofia and mountains",
  },
  {
    slug: "mauritius",
    country: "Mauritius",
    flag: "🇲🇺",
    region: "Indian Ocean",
    category: "flat-rate",
    categoryLabel: "Flat-Rate Program",
    taxAngle: "15% flat income tax; Retired Non-Citizen Permit available",
    program: "Mauritius Retired Non-Citizen Permit",
    bestFor: "Retirees seeking a stable English-speaking tropical island with flat-tax rules",
    cardHook:
      "Mauritius applies a 15% flat personal income tax rate and offers a Retired Non-Citizen Permit for qualifying retirees who transfer sufficient foreign income into Mauritius. The island nation is politically stable, English-speaking, and offers high-quality healthcare and infrastructure.",
    officialLinkLabel: "Mauritius Board of Investment",
    officialLink: "https://edbmauritius.org/",
    seoSummary:
      "Mauritius offers a 15% flat income tax and a Retired Non-Citizen Permit for qualifying retirees. Foreign income must be transferred into Mauritius. Verify current program rules before applying.",
    verificationStatus: "check",
    taxDisplay: "15%",
    taxDisplaySubtext: "flat tax program",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Mauritius tropical island and lagoon",
  },
  {
    slug: "georgia",
    country: "Georgia",
    flag: "🇬🇪",
    region: "Eastern Europe / Caucasus",
    category: "flat-rate",
    categoryLabel: "Flat-Rate Program",
    taxAngle: "20% flat income tax on locally-sourced income; foreign income may not be taxed",
    program: "Georgia 1-Year Renewable Residency",
    bestFor: "Retirees seeking low costs and European city lifestyle in Tbilisi",
    cardHook:
      "Georgia (the country) applies a flat 20% income tax on locally-sourced income, with potential exemptions for foreign-source income under its territorial approach. Tbilisi is popular with international retirees for its low costs, warm hospitality, and modern amenities.",
    officialLinkLabel: "Georgia Revenue Service",
    officialLink: "https://rs.ge/",
    seoSummary:
      "Georgia (country) offers a simple flat-tax territorial system. Foreign-source income may not be taxed locally. Verify current rules and residency requirements with official sources.",
    verificationStatus: "check",
    taxDisplay: "20%",
    taxDisplaySubtext: "local income tax",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Tbilisi Georgia old town and mountains",
  },
  {
    slug: "montenegro",
    country: "Montenegro",
    flag: "🇲🇪",
    region: "Balkans / Eastern Europe",
    category: "flat-rate",
    categoryLabel: "Flat-Rate Program",
    taxAngle: "9–15% flat personal income tax rate; EU accession candidate",
    program: "Temporary Residency / EU Candidate Country Pathway",
    bestFor: "Retirees seeking low taxes, Adriatic coast access, and EU pathway",
    cardHook:
      "Montenegro applies a flat personal income tax of 9% on income up to a threshold and 15% above it — among the lowest in Europe. As an EU candidate country, it offers potential future EU membership benefits. Verify how foreign income types are treated under current Montenegrin tax rules.",
    officialLinkLabel: "Montenegro Tax Administration",
    officialLink: "https://www.irs.gov/individuals/international-taxpayers",
    seoSummary:
      "Montenegro has a 9–15% flat income tax rate, among the lowest in Europe. Foreign income treatment depends on residency status and income type. Verify official rules with Montenegro tax authorities.",
    verificationStatus: "check",
    taxDisplay: "9–15%",
    taxDisplaySubtext: "flat income tax",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Montenegro Bay of Kotor",
  },

  // ── TREATY & VARIABLE ─────────────────────────────────────────
  {
    slug: "france",
    country: "France",
    flag: "🇫🇷",
    region: "Western Europe",
    category: "treaty",
    categoryLabel: "Treaty Advantage",
    taxAngle: "US-France treaty addresses pension and Social Security taxation",
    program: "US-France Income Tax Convention",
    bestFor: "Retirees seeking EU residency with strong treaty protections on pension income",
    cardHook:
      "France has a comprehensive income tax treaty with the United States that includes specific provisions for pension income, Social Security benefits, and other retirement-related payments. Treaty rules are complex and depend on your specific income types — consult a qualified advisor familiar with both US and French tax law.",
    officialLinkLabel: "IRS — US Tax Treaties A to Z",
    officialLink:
      "https://www.irs.gov/businesses/international-businesses/united-states-income-tax-treaties-a-to-z",
    seoSummary:
      "The US-France tax treaty addresses how pension income and Social Security benefits are taxed for American retirees living in France. Treaty provisions are complex. Consult a qualified international tax advisor.",
    verificationStatus: "ok",
    taxDisplay: "Treaty",
    taxDisplaySubtext: "U.S. pension rules",
    imageUrl: FALLBACK_IMG,
    imageAlt: "France Paris Eiffel Tower",
  },
  {
    slug: "spain",
    country: "Spain",
    flag: "🇪🇸",
    region: "Mediterranean Europe",
    category: "treaty",
    categoryLabel: "Treaty Advantage",
    taxAngle: "US-Spain treaty; Non-Lucrative Visa for passive-income retirees",
    program: "US-Spain Income Tax Convention / Non-Lucrative Visa",
    bestFor: "Retirees seeking Mediterranean lifestyle with EU residency and treaty clarity",
    cardHook:
      "Spain has a bilateral income tax treaty with the United States and offers the Non-Lucrative Visa — a popular path for American retirees who can demonstrate sufficient passive income. Treaty provisions and Spain's own tax rules can be complex — consult a qualified advisor.",
    officialLinkLabel: "IRS — US Tax Treaties A to Z",
    officialLink:
      "https://www.irs.gov/businesses/international-businesses/united-states-income-tax-treaties-a-to-z",
    seoSummary:
      "The US-Spain tax treaty covers pensions and retirement income. Spain's Non-Lucrative Visa is popular with American retirees. Verify treaty provisions and Non-Lucrative Visa requirements with a qualified advisor.",
    verificationStatus: "ok",
    taxDisplay: "Treaty",
    taxDisplaySubtext: "U.S. pension rules",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Spain Seville architecture",
  },
  {
    slug: "mexico",
    country: "Mexico",
    flag: "🇲🇽",
    region: "Latin America",
    category: "flat-rate",
    categoryLabel: "Flat-Rate Program",
    taxAngle: "US-Mexico tax treaty; residency-based tax treatment",
    program: "Temporary Resident Visa (Visa de Residente Temporal)",
    bestFor: "Retirees seeking proximity to the US with warm climate and low costs",
    cardHook:
      "Mexico has a bilateral tax treaty with the United States that addresses how certain income types are taxed. Mexico's Temporary Resident Visa is widely used by American retirees. Local tax treatment of foreign income depends on residency classification and income type.",
    officialLinkLabel: "Mexico SAT (Tax Administration Service)",
    officialLink: "https://www.sat.gob.mx/",
    seoSummary:
      "Mexico's US tax treaty and Temporary Resident Visa are popular with American retirees. Local tax treatment of foreign income varies by residency status. Verify official rules with SAT Mexico and a qualified advisor.",
    verificationStatus: "check",
    taxDisplay: "Variable",
    taxDisplaySubtext: "treaty + residency rules",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Mexico Oaxaca colonial architecture",
  },
  {
    slug: "thailand",
    country: "Thailand",
    flag: "🇹🇭",
    region: "Southeast Asia",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "Income earned abroad and not remitted may not be taxable locally",
    program: "Thailand Retirement Visa (Non-Immigrant O-A)",
    bestFor: "Retirees aged 50+ seeking low costs and tropical climate",
    cardHook:
      "Thailand offers a Non-Immigrant O-A visa for retirees aged 50 and over. Thailand's tax rules on remitted foreign income have evolved — income remitted to Thailand in the year it is earned may be subject to local tax. Verify current rules with official Thai tax authority.",
    officialLinkLabel: "Thailand Revenue Department",
    officialLink: "https://www.rd.go.th/",
    seoSummary:
      "Thailand retirement visa available from age 50. Local tax treatment of remitted foreign income depends on timing and residency rules. Verify current official rules before making decisions.",
    verificationStatus: "check",
    taxDisplay: "Variable",
    taxDisplaySubtext: "remittance rules",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Thailand temple and tropical scenery",
  },
  {
    slug: "dominican-republic",
    country: "Dominican Republic",
    flag: "🇩🇴",
    region: "Caribbean",
    category: "flat-rate",
    categoryLabel: "Flat-Rate Program",
    taxAngle: "Pensionado / Rentista regime may exempt foreign income for qualifying retirees",
    program: "Pensionado / Rentista Residency Visa",
    bestFor: "Retirees seeking Caribbean living with pension-friendly residency incentives",
    cardHook:
      "The Dominican Republic offers a Pensionado and Rentista residency program designed for retirees with qualifying foreign income. Under this regime, qualifying retirees may benefit from favorable treatment on foreign-source pension income. The DR offers beautiful beaches, a low cost of living, and established expat communities.",
    officialLinkLabel: "DGII Dominican Republic (Tax Authority)",
    officialLink: "https://www.dgii.gov.do/",
    seoSummary:
      "The Dominican Republic Pensionado/Rentista program offers potential tax benefits for qualifying retirees on foreign pension income. Verify current program rules with official Dominican authorities.",
    verificationStatus: "check",
    taxDisplay: "Pension Benefit",
    taxDisplaySubtext: "retiree visa incentives",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Dominican Republic beach and palm trees",
  },
  {
    slug: "colombia",
    country: "Colombia",
    flag: "🇨🇴",
    region: "South America",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "Pension income may qualify for local tax exemptions",
    program: "Pensioner / Retirement Visa (Visa de Pensionado)",
    bestFor: "Retirees seeking city life in Medellín or Cartagena beach living",
    cardHook:
      "Colombia offers a Pensioner Visa and a legal framework that may provide favorable treatment for qualifying foreign pension income. Medellín's spring-like climate and modern infrastructure make it one of Latin America's most popular expat hubs.",
    officialLinkLabel: "Migración Colombia",
    officialLink: "https://www.migracioncolombia.gov.co/",
    seoSummary:
      "Colombia Pensioner Visa and favorable pension income tax treatment may be available. Rules depend on residency status and income type. Verify official rules before making residency or tax decisions.",
    verificationStatus: "check",
    taxDisplay: "Variable",
    taxDisplaySubtext: "pension tax benefit",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Colombia Medellin mountains",
  },
  {
    slug: "ireland",
    country: "Ireland",
    flag: "🇮🇪",
    region: "Western Europe",
    category: "treaty",
    categoryLabel: "Treaty Advantage",
    taxAngle: "US-Ireland treaty; potential remittance basis for qualifying residents",
    program: "US-Ireland Income Tax Convention",
    bestFor: "Retirees with Irish ancestry or those seeking an English-speaking EU base",
    cardHook:
      "Ireland and the United States have a bilateral income tax treaty covering pension income and retirement benefits. Ireland has a separate remittance basis of taxation for qualifying non-domicile residents — a complex area requiring specialist advice. Irish ancestry may ease certain residency pathways.",
    officialLinkLabel: "IRS — US Tax Treaties A to Z",
    officialLink:
      "https://www.irs.gov/businesses/international-businesses/united-states-income-tax-treaties-a-to-z",
    seoSummary:
      "The US-Ireland tax treaty covers pension and retirement income. Ireland's non-dom remittance basis is complex. Ancestry visa and Stamp 0 residency options available. Verify all rules with a qualified international tax advisor.",
    verificationStatus: "ok",
    taxDisplay: "Treaty",
    taxDisplaySubtext: "U.S. pension rules",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Ireland Cliffs of Moher",
  },
  {
    slug: "turkey",
    country: "Turkey",
    flag: "🇹🇷",
    region: "Eastern Europe / Middle East",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "Residency-based tax treatment; US-Turkey treaty exists",
    program: "Turkey Short-Term Residence Permit",
    bestFor: "Retirees seeking Mediterranean and Aegean coast living at very low costs",
    cardHook:
      "Turkey offers a Short-Term Residence Permit accessible to American retirees, with an established expat community in coastal cities like Antalya, Bodrum, and Istanbul. Turkey has a bilateral tax treaty with the United States. Local income tax treatment depends on residency status and income type — verify current rules with Turkish tax authorities.",
    officialLinkLabel: "Turkish Revenue Administration",
    officialLink: "https://www.gib.gov.tr/",
    seoSummary:
      "Turkey offers accessible residence permits for American retirees and has a US tax treaty. Local tax treatment varies by residency status. Verify current rules with Turkish authorities and a qualified advisor.",
    verificationStatus: "check",
    taxDisplay: "Variable",
    taxDisplaySubtext: "residency-based rules",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Turkey Istanbul and Aegean coast",
  },
  {
    slug: "dominica",
    country: "Dominica",
    flag: "🇩🇲",
    region: "Caribbean",
    category: "territorial",
    categoryLabel: "Territorial Tax",
    taxAngle: "Foreign-source income planning opportunities for qualifying residents",
    program: "Dominica Citizenship by Investment / Residency",
    bestFor: "Retirees seeking a Caribbean island base with foreign-income planning options",
    cardHook:
      "The Commonwealth of Dominica — not to be confused with the Dominican Republic — offers a Citizenship by Investment programme and residency options for qualifying individuals. Dominica's tax framework may allow favorable treatment of foreign-source income depending on residency status. Verify current rules with official Dominica authorities.",
    officialLinkLabel: "Dominica Citizenship by Investment Unit",
    officialLink: "https://www.irs.gov/individuals/international-taxpayers",
    seoSummary:
      "Dominica offers citizenship by investment and residency options. Foreign-source income may receive favorable treatment depending on residency status. Verify current program rules before applying.",
    verificationStatus: "check",
    taxDisplay: "Low-tax",
    taxDisplaySubtext: "foreign-income planning",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Dominica Caribbean rainforest island",
  },
  {
    slug: "barbados",
    country: "Barbados",
    flag: "🇧🇧",
    region: "Caribbean",
    category: "treaty",
    categoryLabel: "Treaty Advantage",
    taxAngle: "US-Barbados treaty; Special Entry Permit for qualifying retirees",
    program: "Barbados Special Entry Permit / Welcome Stamp",
    bestFor: "Retirees seeking English-speaking Caribbean living with US treaty protections",
    cardHook:
      "Barbados has a bilateral income tax treaty with the United States and offers a Special Entry Permit for qualifying individuals with sufficient passive income. Barbados is a stable, English-speaking nation with high-quality infrastructure and healthcare. Treaty provisions should be reviewed with a qualified international tax advisor.",
    officialLinkLabel: "IRS — US Tax Treaties A to Z",
    officialLink:
      "https://www.irs.gov/businesses/international-businesses/united-states-income-tax-treaties-a-to-z",
    seoSummary:
      "The US-Barbados tax treaty provides rules for pension and retirement income. Barbados Special Entry Permit available for qualifying retirees. Verify current visa requirements and treaty rules with a qualified advisor.",
    verificationStatus: "ok",
    taxDisplay: "Treaty",
    taxDisplaySubtext: "special entry permit",
    imageUrl: FALLBACK_IMG,
    imageAlt: "Barbados Caribbean beach",
  },
];

export const faqItems: FaqItem[] = [
  {
    question: "Do Americans still pay US taxes when living abroad?",
    answer:
      "Yes. The United States taxes citizens on worldwide income regardless of where they reside. Americans living abroad must generally continue filing US tax returns annually. However, provisions such as the Foreign Earned Income Exclusion (FEIE), Foreign Tax Credit, and bilateral tax treaties may reduce or offset US tax liability in certain circumstances. Your specific situation depends on income type, country of residence, and applicable treaty rules. Always consult a qualified international tax professional.",
  },
  {
    question: "What is a territorial tax system and how does it benefit retirees?",
    answer:
      "Countries with territorial tax systems generally only tax income earned within their borders. For retirees receiving pension income, Social Security, or investment returns sourced from outside the country, this may mean that income is not subject to local taxation. However, rules vary significantly by country, residency classification, and income type. What qualifies as 'foreign-source' income under local law may differ from US definitions. Always verify official rules before making any tax or residency decisions.",
  },
  {
    question: "What is the Foreign Earned Income Exclusion (FEIE)?",
    answer:
      "The FEIE allows qualifying Americans abroad to exclude a portion of foreign-earned income from US federal income tax. For 2024, the exclusion was up to $126,500 per person. It applies only to earned income (wages, self-employment) — not passive income, US pensions, or Social Security benefits. To qualify, you must meet either the Physical Presence Test or the Bona Fide Residence Test. Consult a qualified CPA experienced in expat taxation for your specific circumstances.",
  },
  {
    question: "What is an income tax treaty and how does it protect retirees abroad?",
    answer:
      "The United States has bilateral income tax treaties with dozens of countries. These treaties can determine which country has the right to tax specific income types — such as government pensions, Social Security benefits, dividends, or capital gains — and at what rates. Treaty provisions are complex, vary by country and income type, and depend on your residency status. Simply living in a treaty country does not automatically guarantee all treaty benefits. A qualified international tax advisor should review your specific situation.",
  },
  {
    question: "What is the Foreign Tax Credit and can it eliminate double taxation?",
    answer:
      "If you pay income tax to a foreign country, you may be eligible to claim a US Foreign Tax Credit (FTC) to reduce your US tax liability dollar-for-dollar on the same income. The FTC can help prevent double taxation — paying tax on the same income twice. However, it is subject to limitations, category rules, and complex IRS regulations. It does not apply to all tax types. A qualified CPA specializing in expat taxation should evaluate your individual situation.",
  },
  {
    question: "What documents do I typically need to establish foreign tax residency?",
    answer:
      "Document requirements vary significantly by country and individual circumstances. Common documents may include: proof of long-term housing (lease or deed), proof of pension or retirement income, certified bank statements, prior-year US tax returns, valid passport and identification, apostilled criminal background check, medical insurance documentation, and proof of local residency registration. In many countries, certified translations of US documents are also required. Always consult an immigration attorney and local tax advisor before applying.",
  },
  {
    question: "Are Social Security benefits taxable when I live abroad?",
    answer:
      "Social Security benefits may remain subject to US income tax for Americans living abroad — standard US rules generally apply. However, some bilateral tax treaties include specific provisions that can affect how Social Security is taxed in your country of residence. Rules vary by treaty country and individual circumstances. Verify current IRS guidance, the applicable treaty provisions, and consult a qualified international tax advisor.",
  },
  {
    question: "Should I consult a tax professional before retiring abroad?",
    answer:
      "Yes — strongly recommended. International tax situations are among the most complex in personal finance. Laws change frequently, treaty provisions are nuanced, FBAR and FATCA compliance adds reporting obligations, and individual circumstances vary widely. Working with a CPA who specializes in US expat taxation, plus a qualified local advisor in your destination country, is strongly recommended before making any residency or tax decisions. This guide is for educational purposes only and does not constitute tax or legal advice.",
  },
];
