import Link from "next/link";
import { getAllMarkdownSlugs, parseMarkdownArticle } from "@/lib/markdown";
import { getAllArticles } from "@/lib/data";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const dynamic = "force-static";

export default function ArticlesPage() {
  // ── Markdown articles (auto-generated by Make.com) ──
  const mdSlugs = getAllMarkdownSlugs();
  const mdArticles = mdSlugs
    .map((slug) => parseMarkdownArticle(slug))
    .filter(Boolean)
    .map((a) => ({
      slug: a!.slug,
      title: a!.title,
      category: a!.category,
      intro: a!.intro,
      date: a!.date,
      image: a!.items[0]?.image || "",
      source: "markdown" as const,
    }));

  // ── Hardcoded data.ts articles ──
  const dataArticles = getAllArticles().map((a) => ({
    slug: a.slug,
    title: a.title,
    category: typeof a.category === "string" ? a.category : a.category?.name || "Travel",
    intro: a.intro || "",
    date: a.date || "",
    image: a.image || "",
    source: "data" as const,
  }));

  // Deduplicate: Markdown takes priority
  const mdSlugsSet = new Set(mdArticles.map((a) => a.slug));
  const allArticles = [
    ...mdArticles,
    ...dataArticles.filter((a) => !mdSlugsSet.has(a.slug)),
  ];

  return (
    <div style={{ minHeight: "100vh", background: "#faf7f2", color: "#2c2c2c" }}>
      <Header />

      <main style={{ maxWidth: "1100px", margin: "0 auto", padding: "60px 24px 80px" }}>
        {/* Page header */}
        <div
          style={{
            borderBottom: "3px solid #d4af37",
            paddingBottom: "24px",
            marginBottom: "48px",
          }}
        >
          <div
            style={{
              fontFamily: "Arial, sans-serif",
              fontSize: "0.68rem",
              fontWeight: 800,
              letterSpacing: "3px",
              textTransform: "uppercase",
              color: "#d4af37",
              marginBottom: "10px",
            }}
          >
            Golden Horizons
          </div>
          <h1
            style={{
              fontFamily: "Georgia, 'Times New Roman', serif",
              fontSize: "2.4rem",
              fontWeight: "bold",
              color: "#1a3a2a",
              lineHeight: 1.2,
              marginBottom: "12px",
            }}
          >
            All Articles
          </h1>
          <p
            style={{
              fontFamily: "Georgia, serif",
              fontSize: "1rem",
              color: "#666",
              maxWidth: "600px",
            }}
          >
            Guides, rankings, and stories to help you plan your best retirement abroad.
          </p>
        </div>

        {/* Article grid */}
        {allArticles.length === 0 ? (
          <p style={{ fontFamily: "Georgia, serif", color: "#888", fontSize: "1rem" }}>
            No articles published yet. Check back soon.
          </p>
        ) : (
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
              gap: "32px",
            }}
          >
            {allArticles.map((article) => (
              <Link
                key={article.slug}
                href={`/article/${article.slug}`}
                style={{ textDecoration: "none", color: "inherit" }}
              >
                <div
                  style={{
                    background: "#fff",
                    borderRadius: "8px",
                    overflow: "hidden",
                    boxShadow: "0 2px 12px rgba(0,0,0,0.07)",
                    transition: "transform 0.2s, box-shadow 0.2s",
                    height: "100%",
                    display: "flex",
                    flexDirection: "column",
                  }}
                  onMouseEnter={(e) => {
                    (e.currentTarget as HTMLDivElement).style.transform = "translateY(-4px)";
                    (e.currentTarget as HTMLDivElement).style.boxShadow =
                      "0 8px 24px rgba(0,0,0,0.13)";
                  }}
                  onMouseLeave={(e) => {
                    (e.currentTarget as HTMLDivElement).style.transform = "translateY(0)";
                    (e.currentTarget as HTMLDivElement).style.boxShadow =
                      "0 2px 12px rgba(0,0,0,0.07)";
                  }}
                >
                  {/* Card image */}
                  <div
                    style={{
                      width: "100%",
                      height: "200px",
                      overflow: "hidden",
                      background: "#c8d8c0",
                      flexShrink: 0,
                    }}
                  >
                    {article.image ? (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img
                        src={article.image}
                        alt={article.title}
                        loading="lazy"
                        style={{
                          width: "100%",
                          height: "100%",
                          objectFit: "cover",
                          display: "block",
                        }}
                      />
                    ) : (
                      <div
                        style={{
                          width: "100%",
                          height: "100%",
                          background: "linear-gradient(135deg, #1a3a2a 0%, #2d5a3d 100%)",
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                        }}
                      >
                        <span
                          style={{
                            fontFamily: "Georgia, serif",
                            color: "#d4af37",
                            fontSize: "1.1rem",
                            fontWeight: "bold",
                            letterSpacing: "2px",
                          }}
                        >
                          GH
                        </span>
                      </div>
                    )}
                  </div>

                  {/* Card body */}
                  <div style={{ padding: "20px 22px 24px", flex: 1, display: "flex", flexDirection: "column" }}>
                    {/* Category */}
                    <div
                      style={{
                        fontFamily: "Arial, sans-serif",
                        fontSize: "0.65rem",
                        fontWeight: 800,
                        letterSpacing: "2px",
                        textTransform: "uppercase",
                        color: "#d4af37",
                        marginBottom: "8px",
                      }}
                    >
                      {article.category}
                    </div>

                    {/* Title */}
                    <h2
                      style={{
                        fontFamily: "Georgia, 'Times New Roman', serif",
                        fontSize: "1.1rem",
                        fontWeight: "bold",
                        color: "#1a3a2a",
                        lineHeight: 1.35,
                        marginBottom: "10px",
                        flex: 1,
                      }}
                    >
                      {article.title}
                    </h2>

                    {/* Intro excerpt */}
                    {article.intro && (
                      <p
                        style={{
                          fontFamily: "Georgia, serif",
                          fontSize: "0.85rem",
                          color: "#666",
                          lineHeight: 1.55,
                          marginBottom: "14px",
                          display: "-webkit-box",
                          WebkitLineClamp: 2,
                          WebkitBoxOrient: "vertical",
                          overflow: "hidden",
                        }}
                      >
                        {article.intro}
                      </p>
                    )}

                    {/* Read more */}
                    <div
                      style={{
                        fontFamily: "Arial, sans-serif",
                        fontSize: "0.75rem",
                        fontWeight: 700,
                        color: "#1a3a2a",
                        letterSpacing: "0.5px",
                        display: "flex",
                        alignItems: "center",
                        gap: "4px",
                      }}
                    >
                      Read article →
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        )}
      </main>

      <Footer />
    </div>
  );
}
